services:
    # PHP Services container
    app:
        build:
            args:
                user: laravel_user
                uid: 1000

            context: ./
            dockerfile: Dockerfile
        image: laravel_app_image
        container_name: laravel_app_php_container
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel_app_network

    # Nginx service
    webserver:
        image: nginx:alpine
        container_name: laravel_app_webserver_container
        restart: unless-stopped
        ports:
            - "6162:80"
        networks:
            - laravel_app_network

networks:
    laravel_app_network:
        driver: bridge
